server:
  address: 0.0.0.0
  port: 80
  servlet:
    context-path:

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:mysql://localhost:3306/jboot?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    url: jdbc:log4jdbc:mysql://localhost:3306/jboot?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: root
    hikari:
      username: root
      password: root
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数,默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期,值0表示无限生命周期,默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒,即30000
      connection-timeout: 30000
      #连接池每分配一条连接前执行的查询语句（如：SELECT 1），以验证该连接是否是有效的。如果你的驱动程序支持 JDBC4,HikariCP 强烈建议我们不要设置此属性
#      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template: false
    check-template-location: false
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:templates/
    suffix: .html
    enabled: true
logging:
  level:
    org:
      jot: debug
  file:
    path: ../logs/jboot


